jina-ai/jina-hubble-sdk

Makefile
README.md
hubble/utils/auth.py
hubble/utils/config.py
tests/unit/utils/test_config.py

- refactor: extract config class
- feat: add logout function

feat: add logout function

---

hubble/client/client.py
hubble/utils/api_utils.py
hubble/utils/auth.py

Also use `get_base_url` in `auth.py`

feat: use `JINA_HUBBLE_REGISTRY` env var to get api host

---

hubble/utils/auth.py
hubble/utils/template/logged_in_page.html

Related https://github.com/jina-ai/hubble/issues/354

feat(login): after login page ui improvement

---

hubble/client/base.py
hubble/client/client.py

fix: remove timeout

---

hubble/client/base.py
hubble/client/client.py
hubble/utils/pbar.py
requirements.txt
tests/integration/test_client.py

feat(artifact): show progress bar for uploading & downloading

---

README.md

docs(readme): remove timeout accordingly

---

.github/workflows/style-and-test-check.yml
hubble/settings.py
hubble/utils/api_utils.py
tests/unit/utils/test_api_utils.py

Related to: https://github.com/jina-ai/hubble/issues/434
Close #5

feat: use api.hubble.jina.ai

---

README.md
hubble/client/client.py
hubble/client/endpoints.py
tests/integration/test_client.py

feat(artifact): list artifacts method

---

.github/workflows/release.yml
.github/workflows/style-and-test-check.yml
tests/conftest.py

ci: JINA_HUBBLE_REGISTRY replace HUBBLE_ENVIRONMENT

---

hubble/__init__.py
hubble/utils/auth.py
requirements.txt

This PR should fix hubble login in notebook:

fix: asyncio login logout in notebook

---

hubble/utils/auth.py
hubble/utils/google_colab.py

Allows login in Google Colab
Close: #44

feat(login): remove localhost for login

---

README.md

docs(faq): add asyncio problem in Google Colab

---

hubble/__init__.py
hubble/api.py
hubble/utils/auth.py

fix(wording): correct english

---

hubble/excepts.py

feat(excepts): add maximum upload size reached error

---

hubble/api.py
hubble/utils/auth.py
tests/unit/utils/test_auth.py

feat(auth): check for existing token before login

---

tests/unit/executor/parser/test_new.py
tests/unit/executor/parser/test_pushpull.py

test: copied tests for executor cli parser from jina core

---

hubble/executor/hubio.py
tests/unit/executor/test_hubio.py

Various fixes for strings displayed in CLI
- fix: capitalize executor
- fix: other fixes
- fix: final fixes

fix: strings english

---

README.md
hubble/__init__.py
hubble/utils/auth.py
requirements-dev.txt
tests/unit/utils/test_auth.py

Ref #78 
**This PR improves the login experience in notebook-like environments (jupyter, google colab).**
There are some images of the new design, attached below.
**Login prompt**
**Authenticate in browser prompt**
**Success**
**Error**

feat: notebook login

---

hubble/utils/auth.py

Ref #78 
This PR is to improve the UX of the `notebook_login()` feature.

refactor: improve notebook login ui

---

hubble/executor/hubio.py

Improve the print result of hub list

fix: improve the print result of hub list

---

hubble/executor/hubio.py
hubble/utils/auth.py

change hub links to cloud.jina.ai

fix: change hub link to cloud.jina.ai

---

hubble/__init__.py
hubble/utils/auth.py
hubble/utils/notebook.py
requirements.txt
tests/unit/utils/test_notebook.py

feat: automatic env detection for hubble login

---

hubble/client/base.py
hubble/utils/api_utils.py

Add session-id as tracking id in request's header for better error tracking

refactor: add session-id in request's header for better error tracking

---

hubble/utils/auth.py

Ref #101 
The `login_sync()` function did not attempt to open the browser automatically for log in, so when we started using `login_sync()` as the main login function, we've lost the functionality of opening the browser automatically when calling `jina.auth.login()`. 
Changes: 
- added the code to open the browser automatically for log to `login_sync()`
- unified `login_sync()` and `login()` functions, now `login_sync()` shows the same messages as `login()` when not used in interactive mode

fix: try to open browser in login_sync() func

---

hubble/client/client.py
hubble/client/endpoints.py
tests/integration/test_client.py

feat: add update artifact method

---

hubble/api.py
hubble/client/client.py
hubble/utils/auth.py
tests/unit/utils/test_auth.py

fix: fallback to name if nickname is missing

---

hubble/__init__.py
hubble/utils/auth.py

fix: show username in login status message

---

hubble/executor/hubio.py
tests/unit/executor/test_hubio.py

fix: adapt usage output to new uri

---

hubble/executor/hubio.py
hubble/executor/parsers/push.py
tests/unit/executor/test_hubio.py

https://docs.jina.ai/fundamentals/executor/hub/push-executor/#use-environment-variables

fix(build-env): allow multiple env be passed as described in docs

---

hubble/executor/helper.py
hubble/executor/hubapi.py
hubble/executor/hubio.py
requirements.txt
tests/unit/executor/dummy_executor/config.yml
tests/unit/executor/test_hubapi.py
tests/unit/executor/test_hubio.py

fix: remove executor id and secret caching

---

hubble/__init__.py

Context: 
https://jinaai.slack.com/archives/C023A7RAPGR/p1670821716958019

feat: detect interactive shell and propose login

---

tests/integration/test_client.py

The integration test of `upload_artifact` with name is missing in #143 , i added it back.

test: add upload artifact with name test

---

hubble/executor/hubio.py
tests/unit/executor/test_hubio.py

Put prefer-platform behind the local cache

fix(pull): put prefer-platform behind local cache

---

hubble/__init__.py
hubble/utils/auth.py

This need to come after https://github.com/jina-ai/hubble/pull/850

fix(login): remove provider assertion, prompt user for login

---

hubble/client/base.py
hubble/payment/base.py
hubble/payment/client.py
hubble/payment/endpoints.py
hubble/payment/jwks.py
hubble/payment/session.py
hubble/utils/api_utils.py
requirements.txt
tests/unit/payment/test_payment_client.py

Ref: https://github.com/jina-ai/hubble/issues/853
The goal is to implement basic payment functions in the Hubble SDK.

feat: add payment module with basic payment function for apps

---

hubble/client/client.py
hubble/client/endpoints.py
tests/integration/test_client.py

In this pr I added `get_user_raw_info` to hubble SDK in order to access the expiration date of token.

feat: add get_user_raw_info

---

hubble/payment/client.py

Ref: https://github.com/jina-ai/hubble/issues/882

feat: adapt payment client to latest payment API

---

hubble/client/client.py

document the new variant param

doc(get_user_info): document the new variant param
