jina-ai/jina-hubble-sdk

- hubble/utils/auth.py
- tests/unit/utils/config.json
- tests/unit/utils/test_config.py
Discussed with @delgermurun , in the hubble python client, we first try to get token from env, then get token from configuration. This is needed inside Finetuner.runner, since we can not login, but we pass token as environment variable. We need a patch release after this PR.
link to https://github.com/jina-ai/finetuner.fit/issues/188 and https://github.com/jina-ai/finetuner-api/pull/56
> feat: allow get token from env

- hubble/utils/auth.py
The logout function did not work, because there was a double slash in the url. To make sure that a valid url is constructed, I used the `urljoin`function.
> fix hubble logout

- hubble/client/client.py
- tests/integration/test_client.py
Support upload an byteIO object. 
Why? In Finetuner, we want to reserve an `artifact_id` by uploading a placeholder object without creating a real object.
The impact: when calling `upload_artifact` with `path`, please replace `path` to `f`.
> feat: support upload bytesio

- README.md
BREAKING CHANGE:
parameter `path` is replaced by `f`, which can not only accept a path but also a `io.BytesIO` instance
> docs(readme): update the usage of `upload_artifact`

- hubble/client/client.py
An authentication error is raised after the whole file is sent if the user is not logged in, which takes a lot of time.
So trying to fetch user info before the upload request, which will produce the same error if the user is not logged in.
Fixes #24
> pref(artifact): check login before upload

- .github/workflows/release.yml
- .github/workflows/style-and-test-check.yml
- README.md
- hubble/client/base.py
- tests/integration/test_client.py
- tests/unit/client/test_client.py
- tests/unit/utils/test_api_utils.py
- tests/unit/utils/test_config.py
Don't throw error during new Client, if there
is no authentication info. Instead, throw error when
actually calling according API.
Related to: https://github.com/jina-ai/auth/issues/2
---
@bwanglzu This is a breaking change, please change the usage accordingly in finetuner.
> feat: change the way throw error

- README.md
- hubble/client/client.py
- tests/integration/test_client.py
allow download as bytes io object.
Note: this is a breaking change to `download_artifact`.
> feat: allow download as bytesio obj

- hubble/__init__.py
- requirements-dev.txt
- tests/unit/client/test_client.py
Extend the `login_required` decorator to also check if the token is valid or expired and display the correct message.
> fix: extend login to expired tokens

- hubble/utils/auth.py
- tests/unit/utils/test_auth.py
- tests/unit/utils/test_config.py
Don't dismiss the token session if the token is from the environment variable.
When logout is called, it means to remove the token from the config file.
> fix: local logout should not dismiss token session

- hubble/api.py
- hubble/client/client.py
- hubble/client/endpoints.py
- hubble/dockerauth.py
- hubble/utils/auth.py
- setup.cfg
- setup.py
- tests/integration/test_client.py
This deploys `docker credentials helper` for hubble internal registries when the user logs in.
For the big picture you can refer to https://github.com/jina-ai/hubble/blob/master/docs/docker-authentication-layer.md
This is for the jina client to properly pull from hubble internal private docker registries.
It loads the hubble auth token and sends this token into docker daemon context, which will eventually requests an access token from hubble API server with the auth token.
For the concept of docker credentials helper, please refer to https://docs.docker.com/engine/reference/commandline/login/#credential-helpers
> feat: docker authentication plugin

- hubble/dockerauth.py
Looks like docker config file defaults to 2 space indent. 
Also add the missing line break at the end of file.
> fix: json output indent and eof line break

- hubble/utils/auth.py
rich's print method does not properly print links in colab.
Specifically, extra query string parameters are not passed in the link address although rendered correctly.
This PR reverts to system print for printing links (we just use emoji)
> fix: fix print authentication link

- hubble/executor/hubio.py
- tests/unit/executor/test_hubio.py
Fixes https://github.com/jina-ai/hubble/issues/605
Now, width is dynamic.. Depending on the length of the line, it will grow.
Will show `...` if it doesn't fit into the terminal width.
> fix: in terminal show full line for executor usage

- hubble/executor/helper.py
the cache path from  ~/.cache/hubble.executor/  to  ~/.cache/jina
> fix: fix the cache path to ~/.cache/jina

- hubble/utils/auth.py
This `post_success` callable event should enable Finetuner client execute some custom function after hubble login succeed.  Since `notebook_login` is non-blocking, we'll have an issue to perform follow-up activities.
see [here](https://github.com/jina-ai/finetuner/pull/576/files#diff-7de38a8a66d22913731b9375e96563a19e4deef2dbcc2c7bde98f4ed49e72072R38)
See it lively:
> feat: add post success callable to login success callback

- hubble/api.py
- hubble/client/base.py
- hubble/client/client.py
- hubble/executor/hubio.py
- hubble/utils/api_utils.py
- hubble/utils/auth.py
- tests/unit/utils/test_api_utils.py
When a response body is not JSON, we can't parse it. Therefore, we cannot see any response details.
It makes debugging almost impossible when something is wrong.
```
2022-10-20T11:09:59.795Z
resp = client.upload_artifact(
2022-10-20T11:09:59.795Z
File "/usr/local/lib/python3.8/site-packages/hubble/client/client.py", line 146, in upload_artifact
2022-10-20T11:09:59.795Z
return self.handle_request(
2022-10-20T11:09:59.795Z
File "/usr/local/lib/python3.8/site-packages/hubble/client/base.py", line 82, in handle_request
2022-10-20T11:09:59.795Z
self._handle_error_request(resp)
2022-10-20T11:09:59.795Z
File "/usr/local/lib/python3.8/site-packages/hubble/client/base.py", line 41, in _handle_error_request
2022-10-20T11:09:59.795Z
resp = resp.json()
2022-10-20T11:09:59.795Z
File …
```
> fix: response json decode error

- hubble/executor/helper.py
- hubble/executor/hubio.py
Issues with the hubble sdk such as `jina hub push` should be reported in jina-hubble-sdk instead of the jina repository
Fixes #91
> fix: change issue URLs to point to hubble-sdk

- hubble/utils/auth.py
Ref #121 
This PR updates the interactive login success message.
> fix: update interactive login success message

- hubble/utils/auth.py
Ref: #131 
`notebook_login` is not calling `post_success` callback when pre-login procedure is successful.
_This is the case when an existing token or PAT is used to login the user ..._
> fix: call post_success in notebook_login where necessary

- .github/workflows/nightly-tests.yml
- .github/workflows/style-and-test-check.yml
Closes #135 
Installs the latest versions of `jina`, `docarray` and `jcloud` with current `hubble-sdk`. Then tries to import those.
> chore: add ci check for jina ecosystem packages compatibility

- hubble/client/client.py
- tests/integration/test_client.py
This PR should allow user to upload an artifact with a `name`, similar as `DocumentArray.push(name='da-name')`
> feat: allow upload artifact with name

- hubble/executor/helper.py
- hubble/executor/hubio.py
- hubble/executor/parsers/pull.py
- hubble/executor/parsers/push.py
- tests/unit/executor/test_hubio.py
This is to support multi-platform build for executors.
Depending on the server implementation the supported platforms are a subset of Docker platforms: https://docs.docker.com/build/building/multi-platform/
As the supported platforms may be changed by the server, this parameter is not checked on the client side.
> feat: executor push with optional platform param

- hubble/executor/parsers/pull.py
Jina pod is having its own version of mixin_hub_pull_options_parser. This aims to let them import from hubble
> fix: move `--install-requirements` from hub pull options

- hubble/executor/hubio.py
It turned out Hubio.pull() is used in many places inside jina core.
To fix the potential issue of unparsed arguments, safeguard parameters with `getattr()`
> fix(pull): args

- hubble/api.py
- hubble/parsers/token.py
feat: allow raw display of hub token
usage: jina auth token  create my-token --format raw
This will allow using jina auth token create cli from the shell and parsing results
> feat: allow raw display of hub token

- hubble/executor/hubio.py
Needed to hide the `Published` panel in langchain-serve, which adds confusion to the user.
> chore: hide panel if env var is set
